// Generated by Classiq.
// Classiq version: 0.29.1
// Creation timestamp: 2023-10-01T20:46:26.073297+00:00
// Random seed: 2246252538

OPENQASM 2.0;
include "qelib1.inc";
gate global_phase q0 {
  p(2*pi) q0;
  rz(-2*pi) q0;
}

gate grover_search_repeat_iteration_grover_operator_u q0 {
  global_phase q0;
  u(0,0,0) q0;
}

gate grover_search_repeat_iteration_grover_operator_sp_op_uniform_superposition_apply_to_all_repeat_iteration_2_gate_operand q0 {
  h q0;
}

gate grover_search_repeat_iteration_grover_operator_sp_op_uniform_superposition_apply_to_all_repeat_iteration_2 q0,q1,q2 {
  grover_search_repeat_iteration_grover_operator_sp_op_uniform_superposition_apply_to_all_repeat_iteration_2_gate_operand q2;
}

gate grover_search_repeat_iteration_grover_operator_sp_op_uniform_superposition_apply_to_all_repeat_iteration_1_gate_operand q0 {
  h q0;
}

gate grover_search_repeat_iteration_grover_operator_sp_op_uniform_superposition_apply_to_all_repeat_iteration_1 q0,q1,q2 {
  grover_search_repeat_iteration_grover_operator_sp_op_uniform_superposition_apply_to_all_repeat_iteration_1_gate_operand q1;
}

gate grover_search_repeat_iteration_grover_operator_sp_op_uniform_superposition_apply_to_all_repeat_iteration_0_gate_operand q0 {
  h q0;
}

gate grover_search_repeat_iteration_grover_operator_sp_op_uniform_superposition_apply_to_all_repeat_iteration_0 q0,q1,q2 {
  grover_search_repeat_iteration_grover_operator_sp_op_uniform_superposition_apply_to_all_repeat_iteration_0_gate_operand q0;
}

gate grover_search_repeat_iteration_grover_operator_sp_op_uniform_superposition_apply_to_all_repeat q0,q1,q2 {
  grover_search_repeat_iteration_grover_operator_sp_op_uniform_superposition_apply_to_all_repeat_iteration_0 q0,q1,q2;
  grover_search_repeat_iteration_grover_operator_sp_op_uniform_superposition_apply_to_all_repeat_iteration_1 q0,q1,q2;
  grover_search_repeat_iteration_grover_operator_sp_op_uniform_superposition_apply_to_all_repeat_iteration_2 q0,q1,q2;
}

gate grover_search_repeat_iteration_grover_operator_sp_op_uniform_superposition_apply_to_all q0,q1,q2 {
  grover_search_repeat_iteration_grover_operator_sp_op_uniform_superposition_apply_to_all_repeat q0,q1,q2;
}

gate grover_search_repeat_iteration_grover_operator_sp_op_uniform_superposition q0,q1,q2 {
  grover_search_repeat_iteration_grover_operator_sp_op_uniform_superposition_apply_to_all q0,q1,q2;
}

gate grover_search_repeat_iteration_grover_operator_sp_op q0,q1,q2 {
  grover_search_repeat_iteration_grover_operator_sp_op_uniform_superposition q0,q1,q2;
}

gate grover_search_repeat_iteration_grover_operator_grover_diffuser_apply_to_all_1_repeat_iteration_2_gate_operand q0 {
  x q0;
}

gate grover_search_repeat_iteration_grover_operator_grover_diffuser_apply_to_all_1_repeat_iteration_2 q0,q1,q2 {
  grover_search_repeat_iteration_grover_operator_grover_diffuser_apply_to_all_1_repeat_iteration_2_gate_operand q2;
}

gate grover_search_repeat_iteration_grover_operator_grover_diffuser_apply_to_all_1_repeat_iteration_1_gate_operand q0 {
  x q0;
}

gate grover_search_repeat_iteration_grover_operator_grover_diffuser_apply_to_all_1_repeat_iteration_1 q0,q1,q2 {
  grover_search_repeat_iteration_grover_operator_grover_diffuser_apply_to_all_1_repeat_iteration_1_gate_operand q1;
}

gate grover_search_repeat_iteration_grover_operator_grover_diffuser_apply_to_all_1_repeat_iteration_0_gate_operand q0 {
  x q0;
}

gate grover_search_repeat_iteration_grover_operator_grover_diffuser_apply_to_all_1_repeat_iteration_0 q0,q1,q2 {
  grover_search_repeat_iteration_grover_operator_grover_diffuser_apply_to_all_1_repeat_iteration_0_gate_operand q0;
}

gate grover_search_repeat_iteration_grover_operator_grover_diffuser_apply_to_all_1_repeat q0,q1,q2 {
  grover_search_repeat_iteration_grover_operator_grover_diffuser_apply_to_all_1_repeat_iteration_0 q0,q1,q2;
  grover_search_repeat_iteration_grover_operator_grover_diffuser_apply_to_all_1_repeat_iteration_1 q0,q1,q2;
  grover_search_repeat_iteration_grover_operator_grover_diffuser_apply_to_all_1_repeat_iteration_2 q0,q1,q2;
}

gate grover_search_repeat_iteration_grover_operator_grover_diffuser_apply_to_all_1 q0,q1,q2 {
  grover_search_repeat_iteration_grover_operator_grover_diffuser_apply_to_all_1_repeat q0,q1,q2;
}

gate ccz q0,q1,q2 {
  p(pi/4) q1;
  p(pi/4) q2;
  cx q1,q2;
  u(0,0,-pi/4) q2;
  cx q1,q2;
  u(0,0,0) q2;
  cx q1,q0;
  p(-pi/4) q0;
  p(pi/4) q2;
  cx q0,q2;
  u(0,0,pi/4) q2;
  cx q0,q2;
  u(0,-pi/2,0) q2;
  cx q1,q0;
  p(pi/4) q0;
  p(pi/4) q2;
  cx q0,q2;
  u(0,0,-pi/4) q2;
  cx q0,q2;
  u(0,0,0) q2;
}

gate cccircuit_147048 q0,q1,q2 {
  ccz q0,q1,q2;
}

gate grover_search_repeat_iteration_grover_operator_grover_diffuser_operand q0,q1,q2 {
  cccircuit_147048 q0,q1,q2;
}

gate grover_search_repeat_iteration_grover_operator_grover_diffuser_apply_to_all_0_repeat_iteration_2_gate_operand q0 {
  x q0;
}

gate grover_search_repeat_iteration_grover_operator_grover_diffuser_apply_to_all_0_repeat_iteration_2 q0,q1,q2 {
  grover_search_repeat_iteration_grover_operator_grover_diffuser_apply_to_all_0_repeat_iteration_2_gate_operand q2;
}

gate grover_search_repeat_iteration_grover_operator_grover_diffuser_apply_to_all_0_repeat_iteration_1_gate_operand q0 {
  x q0;
}

gate grover_search_repeat_iteration_grover_operator_grover_diffuser_apply_to_all_0_repeat_iteration_1 q0,q1,q2 {
  grover_search_repeat_iteration_grover_operator_grover_diffuser_apply_to_all_0_repeat_iteration_1_gate_operand q1;
}

gate grover_search_repeat_iteration_grover_operator_grover_diffuser_apply_to_all_0_repeat_iteration_0_gate_operand q0 {
  x q0;
}

gate grover_search_repeat_iteration_grover_operator_grover_diffuser_apply_to_all_0_repeat_iteration_0 q0,q1,q2 {
  grover_search_repeat_iteration_grover_operator_grover_diffuser_apply_to_all_0_repeat_iteration_0_gate_operand q0;
}

gate grover_search_repeat_iteration_grover_operator_grover_diffuser_apply_to_all_0_repeat q0,q1,q2 {
  grover_search_repeat_iteration_grover_operator_grover_diffuser_apply_to_all_0_repeat_iteration_0 q0,q1,q2;
  grover_search_repeat_iteration_grover_operator_grover_diffuser_apply_to_all_0_repeat_iteration_1 q0,q1,q2;
  grover_search_repeat_iteration_grover_operator_grover_diffuser_apply_to_all_0_repeat_iteration_2 q0,q1,q2;
}

gate grover_search_repeat_iteration_grover_operator_grover_diffuser_apply_to_all_0 q0,q1,q2 {
  grover_search_repeat_iteration_grover_operator_grover_diffuser_apply_to_all_0_repeat q0,q1,q2;
}

gate grover_search_repeat_iteration_grover_operator_grover_diffuser q0,q1,q2 {
  grover_search_repeat_iteration_grover_operator_grover_diffuser_apply_to_all_0 q0,q1,q2;
  grover_search_repeat_iteration_grover_operator_grover_diffuser_operand q0,q1,q2;
  grover_search_repeat_iteration_grover_operator_grover_diffuser_apply_to_all_1 q0,q1,q2;
}

gate grover_search_repeat_iteration_grover_operator_operand_sp_op_qinverse_uniform_superposition_qinverse_apply_to_all_qinverse_repeat_qinverse_iteration_2_qinverse_gate_operand_qinverse q0 {
  h q0;
}

gate grover_search_repeat_iteration_grover_operator_operand_sp_op_qinverse_uniform_superposition_qinverse_apply_to_all_qinverse_repeat_qinverse_iteration_2_qinverse q0,q1,q2 {
  grover_search_repeat_iteration_grover_operator_operand_sp_op_qinverse_uniform_superposition_qinverse_apply_to_all_qinverse_repeat_qinverse_iteration_2_qinverse_gate_operand_qinverse q0;
}

gate grover_search_repeat_iteration_grover_operator_operand_sp_op_qinverse_uniform_superposition_qinverse_apply_to_all_qinverse_repeat_qinverse_iteration_1_qinverse_gate_operand_qinverse q0 {
  h q0;
}

gate grover_search_repeat_iteration_grover_operator_operand_sp_op_qinverse_uniform_superposition_qinverse_apply_to_all_qinverse_repeat_qinverse_iteration_1_qinverse q0,q1,q2 {
  grover_search_repeat_iteration_grover_operator_operand_sp_op_qinverse_uniform_superposition_qinverse_apply_to_all_qinverse_repeat_qinverse_iteration_1_qinverse_gate_operand_qinverse q1;
}

gate grover_search_repeat_iteration_grover_operator_operand_sp_op_qinverse_uniform_superposition_qinverse_apply_to_all_qinverse_repeat_qinverse_iteration_0_qinverse_gate_operand_qinverse q0 {
  h q0;
}

gate grover_search_repeat_iteration_grover_operator_operand_sp_op_qinverse_uniform_superposition_qinverse_apply_to_all_qinverse_repeat_qinverse_iteration_0_qinverse q0,q1,q2 {
  grover_search_repeat_iteration_grover_operator_operand_sp_op_qinverse_uniform_superposition_qinverse_apply_to_all_qinverse_repeat_qinverse_iteration_0_qinverse_gate_operand_qinverse q2;
}

gate grover_search_repeat_iteration_grover_operator_operand_sp_op_qinverse_uniform_superposition_qinverse_apply_to_all_qinverse_repeat_qinverse q0,q1,q2 {
  grover_search_repeat_iteration_grover_operator_operand_sp_op_qinverse_uniform_superposition_qinverse_apply_to_all_qinverse_repeat_qinverse_iteration_0_qinverse q0,q1,q2;
  grover_search_repeat_iteration_grover_operator_operand_sp_op_qinverse_uniform_superposition_qinverse_apply_to_all_qinverse_repeat_qinverse_iteration_1_qinverse q0,q1,q2;
  grover_search_repeat_iteration_grover_operator_operand_sp_op_qinverse_uniform_superposition_qinverse_apply_to_all_qinverse_repeat_qinverse_iteration_2_qinverse q0,q1,q2;
}

gate grover_search_repeat_iteration_grover_operator_operand_sp_op_qinverse_uniform_superposition_qinverse_apply_to_all_qinverse q0,q1,q2 {
  grover_search_repeat_iteration_grover_operator_operand_sp_op_qinverse_uniform_superposition_qinverse_apply_to_all_qinverse_repeat_qinverse q0,q1,q2;
}

gate grover_search_repeat_iteration_grover_operator_operand_sp_op_qinverse_uniform_superposition_qinverse q0,q1,q2 {
  grover_search_repeat_iteration_grover_operator_operand_sp_op_qinverse_uniform_superposition_qinverse_apply_to_all_qinverse q0,q1,q2;
}

gate grover_search_repeat_iteration_grover_operator_operand_sp_op_qinverse q0,q1,q2 {
  grover_search_repeat_iteration_grover_operator_operand_sp_op_qinverse_uniform_superposition_qinverse q0,q1,q2;
}

gate grover_search_repeat_iteration_grover_operator_operand q0,q1,q2 {
  grover_search_repeat_iteration_grover_operator_operand_sp_op_qinverse q0,q1,q2;
}

gate mcx_140299527967056 q0,q1,q2,q3 {
  h q3;
  p(pi/8) q0;
  p(pi/8) q1;
  p(pi/8) q2;
  p(pi/8) q3;
  cx q0,q1;
  p(-pi/8) q1;
  cx q0,q1;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  p(pi/8) q2;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  h q3;
}

gate mcx_hybrid_gray_code_maslov15_140299526769872 q0,q1,q2,q3 {
  mcx_140299527967056 q0,q1,q2,q3;
}

gate mcx_hybrid_gray_code_maslov15_140299526769872_o6 q0,q1,q2,q3 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140299526769872 q0,q1,q2,q3;
  x q0;
}

gate grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_11_mcx_0_qinverse q0,q1,q2,q3 {
  mcx_hybrid_gray_code_maslov15_140299526769872_o6 q0,q1,q2,q3;
}

gate grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_11 q0,q1,q2,q3 {
  x q0;
  grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_11_mcx_0_qinverse q1,q3,q2,q0;
}

gate mcx_140299526400400 q0,q1,q2,q3 {
  h q3;
  p(pi/8) q0;
  p(pi/8) q1;
  p(pi/8) q2;
  p(pi/8) q3;
  cx q0,q1;
  p(-pi/8) q1;
  cx q0,q1;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  p(pi/8) q2;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  h q3;
}

gate mcx_hybrid_gray_code_maslov15_140299771055440 q0,q1,q2,q3 {
  mcx_140299526400400 q0,q1,q2,q3;
}

gate mcx_hybrid_gray_code_maslov15_140299771055440_o4 q0,q1,q2,q3 {
  x q0;
  x q1;
  mcx_hybrid_gray_code_maslov15_140299771055440 q0,q1,q2,q3;
  x q0;
  x q1;
}

gate grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_10_mcx_0_qinverse q0,q1,q2,q3 {
  mcx_hybrid_gray_code_maslov15_140299771055440_o4 q0,q1,q2,q3;
}

gate grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_10 q0,q1,q2,q3 {
  x q3;
  grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_10_mcx_0_qinverse q0,q1,q2,q3;
}

gate mcx_140299525436112 q0,q1,q2,q3 {
  h q3;
  p(pi/8) q0;
  p(pi/8) q1;
  p(pi/8) q2;
  p(pi/8) q3;
  cx q0,q1;
  p(-pi/8) q1;
  cx q0,q1;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  p(pi/8) q2;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  h q3;
}

gate mcx_hybrid_gray_code_maslov15_140299759706576 q0,q1,q2,q3 {
  mcx_140299525436112 q0,q1,q2,q3;
}

gate mcx_hybrid_gray_code_maslov15_140299759706576_o6 q0,q1,q2,q3 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140299759706576 q0,q1,q2,q3;
  x q0;
}

gate grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_9_mcx_0_qinverse q0,q1,q2,q3 {
  mcx_hybrid_gray_code_maslov15_140299759706576_o6 q0,q1,q2,q3;
}

gate grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_9 q0,q1,q2,q3 {
  x q3;
  grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_9_mcx_0_qinverse q2,q0,q1,q3;
}

gate mcx_140299769841808 q0,q1,q2,q3 {
  h q3;
  p(pi/8) q0;
  p(pi/8) q1;
  p(pi/8) q2;
  p(pi/8) q3;
  cx q0,q1;
  p(-pi/8) q1;
  cx q0,q1;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  p(pi/8) q2;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  h q3;
}

gate mcx_hybrid_gray_code_maslov15_140299319389584 q0,q1,q2,q3 {
  mcx_140299769841808 q0,q1,q2,q3;
}

gate grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_8_mcx_0_qinverse q0,q1,q2,q3 {
  mcx_hybrid_gray_code_maslov15_140299319389584 q0,q1,q2,q3;
}

gate grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_8 q0,q1,q2,q3 {
  x q3;
  grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_8_mcx_0_qinverse q0,q1,q2,q3;
}

gate mcx_140299760277520 q0,q1,q2,q3 {
  h q3;
  p(pi/8) q0;
  p(pi/8) q1;
  p(pi/8) q2;
  p(pi/8) q3;
  cx q0,q1;
  p(-pi/8) q1;
  cx q0,q1;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  p(pi/8) q2;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  h q3;
}

gate mcx_hybrid_gray_code_maslov15_140299759432208 q0,q1,q2,q3 {
  mcx_140299760277520 q0,q1,q2,q3;
}

gate mcx_hybrid_gray_code_maslov15_140299759432208_o4 q0,q1,q2,q3 {
  x q0;
  x q1;
  mcx_hybrid_gray_code_maslov15_140299759432208 q0,q1,q2,q3;
  x q0;
  x q1;
}

gate grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_7_mcx_0_qinverse q0,q1,q2,q3 {
  mcx_hybrid_gray_code_maslov15_140299759432208_o4 q0,q1,q2,q3;
}

gate grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_7 q0,q1,q2,q3 {
  x q3;
  grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_7_mcx_0_qinverse q1,q2,q0,q3;
}

gate mcx_140299526176848 q0,q1,q2,q3 {
  h q3;
  p(pi/8) q0;
  p(pi/8) q1;
  p(pi/8) q2;
  p(pi/8) q3;
  cx q0,q1;
  p(-pi/8) q1;
  cx q0,q1;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  p(pi/8) q2;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  h q3;
}

gate mcx_hybrid_gray_code_maslov15_140300210257680 q0,q1,q2,q3 {
  mcx_140299526176848 q0,q1,q2,q3;
}

gate mcx_hybrid_gray_code_maslov15_140300210257680_o0 q0,q1,q2,q3 {
  x q0;
  x q1;
  x q2;
  mcx_hybrid_gray_code_maslov15_140300210257680 q0,q1,q2,q3;
  x q0;
  x q1;
  x q2;
}

gate grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_6_mcx_0_qinverse q0,q1,q2,q3 {
  mcx_hybrid_gray_code_maslov15_140300210257680_o0 q0,q1,q2,q3;
}

gate grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_6 q0,q1,q2,q3 {
  x q3;
  grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_6_mcx_0_qinverse q0,q1,q2,q3;
}

gate mcu1(param0) q0,q1,q2,q3,q4,q5,q6 {
  cu1(pi/32) q5,q6;
  cx q5,q4;
  cu1(-pi/32) q4,q6;
  cx q5,q4;
  cu1(pi/32) q4,q6;
  cx q4,q3;
  cu1(-pi/32) q3,q6;
  cx q5,q3;
  cu1(pi/32) q3,q6;
  cx q4,q3;
  cu1(-pi/32) q3,q6;
  cx q5,q3;
  cu1(pi/32) q3,q6;
  cx q3,q2;
  cu1(-pi/32) q2,q6;
  cx q5,q2;
  cu1(pi/32) q2,q6;
  cx q4,q2;
  cu1(-pi/32) q2,q6;
  cx q5,q2;
  cu1(pi/32) q2,q6;
  cx q3,q2;
  cu1(-pi/32) q2,q6;
  cx q5,q2;
  cu1(pi/32) q2,q6;
  cx q4,q2;
  cu1(-pi/32) q2,q6;
  cx q5,q2;
  cu1(pi/32) q2,q6;
  cx q2,q1;
  cu1(-pi/32) q1,q6;
  cx q5,q1;
  cu1(pi/32) q1,q6;
  cx q4,q1;
  cu1(-pi/32) q1,q6;
  cx q5,q1;
  cu1(pi/32) q1,q6;
  cx q3,q1;
  cu1(-pi/32) q1,q6;
  cx q5,q1;
  cu1(pi/32) q1,q6;
  cx q4,q1;
  cu1(-pi/32) q1,q6;
  cx q5,q1;
  cu1(pi/32) q1,q6;
  cx q2,q1;
  cu1(-pi/32) q1,q6;
  cx q5,q1;
  cu1(pi/32) q1,q6;
  cx q4,q1;
  cu1(-pi/32) q1,q6;
  cx q5,q1;
  cu1(pi/32) q1,q6;
  cx q3,q1;
  cu1(-pi/32) q1,q6;
  cx q5,q1;
  cu1(pi/32) q1,q6;
  cx q4,q1;
  cu1(-pi/32) q1,q6;
  cx q5,q1;
  cu1(pi/32) q1,q6;
  cx q1,q0;
  cu1(-pi/32) q0,q6;
  cx q5,q0;
  cu1(pi/32) q0,q6;
  cx q4,q0;
  cu1(-pi/32) q0,q6;
  cx q5,q0;
  cu1(pi/32) q0,q6;
  cx q3,q0;
  cu1(-pi/32) q0,q6;
  cx q5,q0;
  cu1(pi/32) q0,q6;
  cx q4,q0;
  cu1(-pi/32) q0,q6;
  cx q5,q0;
  cu1(pi/32) q0,q6;
  cx q2,q0;
  cu1(-pi/32) q0,q6;
  cx q5,q0;
  cu1(pi/32) q0,q6;
  cx q4,q0;
  cu1(-pi/32) q0,q6;
  cx q5,q0;
  cu1(pi/32) q0,q6;
  cx q3,q0;
  cu1(-pi/32) q0,q6;
  cx q5,q0;
  cu1(pi/32) q0,q6;
  cx q4,q0;
  cu1(-pi/32) q0,q6;
  cx q5,q0;
  cu1(pi/32) q0,q6;
  cx q1,q0;
  cu1(-pi/32) q0,q6;
  cx q5,q0;
  cu1(pi/32) q0,q6;
  cx q4,q0;
  cu1(-pi/32) q0,q6;
  cx q5,q0;
  cu1(pi/32) q0,q6;
  cx q3,q0;
  cu1(-pi/32) q0,q6;
  cx q5,q0;
  cu1(pi/32) q0,q6;
  cx q4,q0;
  cu1(-pi/32) q0,q6;
  cx q5,q0;
  cu1(pi/32) q0,q6;
  cx q2,q0;
  cu1(-pi/32) q0,q6;
  cx q5,q0;
  cu1(pi/32) q0,q6;
  cx q4,q0;
  cu1(-pi/32) q0,q6;
  cx q5,q0;
  cu1(pi/32) q0,q6;
  cx q3,q0;
  cu1(-pi/32) q0,q6;
  cx q5,q0;
  cu1(pi/32) q0,q6;
  cx q4,q0;
  cu1(-pi/32) q0,q6;
  cx q5,q0;
  cu1(pi/32) q0,q6;
}

gate mcx_gray q0,q1,q2,q3,q4,q5,q6 {
  h q6;
  mcu1(pi) q0,q1,q2,q3,q4,q5,q6;
  h q6;
}

gate mcx_hybrid_gray_code_maslov15_140299068608592 q0,q1,q2,q3,q4,q5,q6 {
  mcx_gray q0,q1,q2,q3,q4,q5,q6;
}

gate grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicaland_mcx_0 q0,q1,q2,q3,q4,q5,q6 {
  mcx_hybrid_gray_code_maslov15_140299068608592 q0,q1,q2,q3,q4,q5,q6;
}

gate grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicaland q0,q1,q2,q3,q4,q5,q6 {
  grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicaland_mcx_0 q0,q1,q2,q3,q4,q5,q6;
}

gate mcx_140299747420304 q0,q1,q2,q3 {
  h q3;
  p(pi/8) q0;
  p(pi/8) q1;
  p(pi/8) q2;
  p(pi/8) q3;
  cx q0,q1;
  p(-pi/8) q1;
  cx q0,q1;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  p(pi/8) q2;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  h q3;
}

gate mcx_hybrid_gray_code_maslov15_140299529657360 q0,q1,q2,q3 {
  mcx_140299747420304 q0,q1,q2,q3;
}

gate mcx_hybrid_gray_code_maslov15_140299529657360_o6 q0,q1,q2,q3 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140299529657360 q0,q1,q2,q3;
  x q0;
}

gate grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_3_mcx_0_140299320868240 q0,q1,q2,q3 {
  mcx_hybrid_gray_code_maslov15_140299529657360_o6 q0,q1,q2,q3;
}

gate grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_5 q0,q1,q2,q3 {
  grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_3_mcx_0_140299320868240 q1,q0,q2,q3;
  x q3;
}

gate mcx_140299767906256 q0,q1,q2,q3 {
  h q3;
  p(pi/8) q0;
  p(pi/8) q1;
  p(pi/8) q2;
  p(pi/8) q3;
  cx q0,q1;
  p(-pi/8) q1;
  cx q0,q1;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  p(pi/8) q2;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  h q3;
}

gate mcx_hybrid_gray_code_maslov15_140299481624976 q0,q1,q2,q3 {
  mcx_140299767906256 q0,q1,q2,q3;
}

gate mcx_hybrid_gray_code_maslov15_140299481624976_o4 q0,q1,q2,q3 {
  x q0;
  x q1;
  mcx_hybrid_gray_code_maslov15_140299481624976 q0,q1,q2,q3;
  x q0;
  x q1;
}

gate grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_1_mcx_0_140299530289104 q0,q1,q2,q3 {
  mcx_hybrid_gray_code_maslov15_140299481624976_o4 q0,q1,q2,q3;
}

gate grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_4 q0,q1,q2,q3 {
  grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_1_mcx_0_140299530289104 q0,q1,q2,q3;
  x q3;
}

gate mcx_140299481435984 q0,q1,q2,q3 {
  h q3;
  p(pi/8) q0;
  p(pi/8) q1;
  p(pi/8) q2;
  p(pi/8) q3;
  cx q0,q1;
  p(-pi/8) q1;
  cx q0,q1;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  p(pi/8) q2;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  h q3;
}

gate mcx_hybrid_gray_code_maslov15_140299525511248 q0,q1,q2,q3 {
  mcx_140299481435984 q0,q1,q2,q3;
}

gate mcx_hybrid_gray_code_maslov15_140299525511248_o6 q0,q1,q2,q3 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140299525511248 q0,q1,q2,q3;
  x q0;
}

gate grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_3_mcx_0 q0,q1,q2,q3 {
  mcx_hybrid_gray_code_maslov15_140299525511248_o6 q0,q1,q2,q3;
}

gate grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_3 q0,q1,q2,q3 {
  grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_3_mcx_0 q2,q0,q1,q3;
  x q3;
}

gate mcx_140299481740240 q0,q1,q2,q3 {
  h q3;
  p(pi/8) q0;
  p(pi/8) q1;
  p(pi/8) q2;
  p(pi/8) q3;
  cx q0,q1;
  p(-pi/8) q1;
  cx q0,q1;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  p(pi/8) q2;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  h q3;
}

gate mcx_hybrid_gray_code_maslov15_140299760251536 q0,q1,q2,q3 {
  mcx_140299481740240 q0,q1,q2,q3;
}

gate grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_2_mcx_0 q0,q1,q2,q3 {
  mcx_hybrid_gray_code_maslov15_140299760251536 q0,q1,q2,q3;
}

gate grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_2 q0,q1,q2,q3 {
  grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_2_mcx_0 q0,q1,q2,q3;
  x q3;
}

gate mcx_140299320789648 q0,q1,q2,q3 {
  h q3;
  p(pi/8) q0;
  p(pi/8) q1;
  p(pi/8) q2;
  p(pi/8) q3;
  cx q0,q1;
  p(-pi/8) q1;
  cx q0,q1;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  p(pi/8) q2;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  h q3;
}

gate mcx_hybrid_gray_code_maslov15_140299320801616 q0,q1,q2,q3 {
  mcx_140299320789648 q0,q1,q2,q3;
}

gate mcx_hybrid_gray_code_maslov15_140299320801616_o4 q0,q1,q2,q3 {
  x q0;
  x q1;
  mcx_hybrid_gray_code_maslov15_140299320801616 q0,q1,q2,q3;
  x q0;
  x q1;
}

gate grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_1_mcx_0 q0,q1,q2,q3 {
  mcx_hybrid_gray_code_maslov15_140299320801616_o4 q0,q1,q2,q3;
}

gate grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_1 q0,q1,q2,q3 {
  grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_1_mcx_0 q1,q2,q0,q3;
  x q3;
}

gate mcx q0,q1,q2,q3 {
  h q3;
  p(pi/8) q0;
  p(pi/8) q1;
  p(pi/8) q2;
  p(pi/8) q3;
  cx q0,q1;
  p(-pi/8) q1;
  cx q0,q1;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  p(pi/8) q2;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  h q3;
}

gate mcx_hybrid_gray_code_maslov15 q0,q1,q2,q3 {
  mcx q0,q1,q2,q3;
}

gate mcx_hybrid_gray_code_maslov15_o0 q0,q1,q2,q3 {
  x q0;
  x q1;
  x q2;
  mcx_hybrid_gray_code_maslov15 q0,q1,q2,q3;
  x q0;
  x q1;
  x q2;
}

gate grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_0_mcx_0 q0,q1,q2,q3 {
  mcx_hybrid_gray_code_maslov15_o0 q0,q1,q2,q3;
}

gate grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_0 q0,q1,q2,q3 {
  grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_0_mcx_0 q0,q1,q2,q3;
  x q3;
}

gate grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_0 q0,q1,q2,q3;
  grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_1 q0,q1,q2,q4;
  grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_2 q0,q1,q2,q5;
  grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_3 q0,q1,q2,q6;
  grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_4 q0,q1,q2,q7;
  grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_5 q0,q1,q2,q8;
  grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicaland q3,q4,q5,q6,q7,q8,q9;
  grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_6 q0,q1,q2,q3;
  grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_7 q0,q1,q2,q4;
  grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_8 q0,q1,q2,q5;
  grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_9 q0,q1,q2,q6;
  grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_10 q0,q1,q2,q7;
  grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic_logicalor_11 q8,q1,q2,q0;
}

gate grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  x q9;
  h q9;
  grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle_arithmetic q0,q1,q2,q3,q4,q5,q6,q7,q8,q9;
  h q9;
  x q9;
}

gate grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op_arithmeticoracle q0,q1,q2,q3,q4,q5,q6,q7,q8,q9;
}

gate grover_search_repeat_iteration_grover_operator_oracle_op q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  grover_search_repeat_iteration_grover_operator_oracle_op_oracle_op q0,q1,q2,q3,q4,q5,q6,q7,q8,q9;
}

gate grover_search_repeat_iteration_grover_operator q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  grover_search_repeat_iteration_grover_operator_oracle_op q0,q1,q2,q3,q4,q5,q6,q7,q8,q9;
  grover_search_repeat_iteration_grover_operator_operand q0,q1,q2;
  grover_search_repeat_iteration_grover_operator_grover_diffuser q0,q1,q2;
  grover_search_repeat_iteration_grover_operator_sp_op q0,q1,q2;
  grover_search_repeat_iteration_grover_operator_u q0;
}

gate grover_search_repeat_iteration q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  grover_search_repeat_iteration_grover_operator q0,q1,q2,q3,q4,q5,q6,q7,q8,q9;
}

gate grover_search_repeat q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  grover_search_repeat_iteration q0,q1,q2,q3,q4,q5,q6,q7,q8,q9;
}

gate grover_search_uniform_superposition_apply_to_all_repeat_iteration_2_gate_operand q0 {
  h q0;
}

gate grover_search_uniform_superposition_apply_to_all_repeat_iteration_2 q0,q1,q2 {
  grover_search_uniform_superposition_apply_to_all_repeat_iteration_2_gate_operand q2;
}

gate grover_search_uniform_superposition_apply_to_all_repeat_iteration_1_gate_operand q0 {
  h q0;
}

gate grover_search_uniform_superposition_apply_to_all_repeat_iteration_1 q0,q1,q2 {
  grover_search_uniform_superposition_apply_to_all_repeat_iteration_1_gate_operand q1;
}

gate grover_search_uniform_superposition_apply_to_all_repeat_iteration_0_gate_operand q0 {
  h q0;
}

gate grover_search_uniform_superposition_apply_to_all_repeat_iteration_0 q0,q1,q2 {
  grover_search_uniform_superposition_apply_to_all_repeat_iteration_0_gate_operand q0;
}

gate grover_search_uniform_superposition_apply_to_all_repeat q0,q1,q2 {
  grover_search_uniform_superposition_apply_to_all_repeat_iteration_0 q0,q1,q2;
  grover_search_uniform_superposition_apply_to_all_repeat_iteration_1 q0,q1,q2;
  grover_search_uniform_superposition_apply_to_all_repeat_iteration_2 q0,q1,q2;
}

gate grover_search_uniform_superposition_apply_to_all q0,q1,q2 {
  grover_search_uniform_superposition_apply_to_all_repeat q0,q1,q2;
}

gate grover_search_uniform_superposition q0,q1,q2 {
  grover_search_uniform_superposition_apply_to_all q0,q1,q2;
}

gate grover_search q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  grover_search_uniform_superposition q0,q1,q2;
  grover_search_repeat q0,q1,q2,q3,q4,q5,q6,q7,q8,q9;
}

qreg q[10];
grover_search q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7],q[8],q[9];
